# Generated by Django 4.2.4 on 2023-08-17 13:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fileuploads", "0002_alter_uploadedfile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="is_overwritten",
            new_name="inspected",
        ),
        migrations.RemoveField(
            model_name="uploadedfile",
            name="is_new",
        ),
    ]
