# Generated by Django 4.2.4 on 2023-08-17 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fileuploads", "0003_rename_is_overwritten_uploadedfile_inspected_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("massage", models.CharField(max_length=50)),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fileuploads.uploadedfile",
                    ),
                ),
            ],
        ),
    ]
